services:
  truth:
    build: .
    command: python -u /app/app.py
    environment:
      - DATABASE_PATH=/app/data/prices.db
      - API_PORT=8888
      # - ALLORA_VALIDATOR_API_URL=https://allora-api.testnet-1.testnet.allora.network/
      - ALLORA_VALIDATOR_API_URL=https://allora-api.testnet.allora.network/
      - TOKEN=ETH
      - TOKEN_CG_ID=ethereum
    ports:
      - "8888:8888"
    volumes:
      - ./truth-data:/app/data

  updater:
    container_name: update
    build: .
    depends_on:
      - truth
    entrypoint: ["sh", "-c", "while true; sleep 60; do python -u /app/update_app.py; done"]
    environment:
      - DATA_PROVIDER_API_ADDRESS=http://truth:8888

  reputer:
    container_name: reputer
    image: halfdong/allora-offchain-node:1.4
    volumes:
      - ./worker-data:/data
    depends_on:
      - truth
    env_file:
      - ./worker-data/env_file

  loss:
    container_name: loss
    image: alloranetwork/allora-standard-loss-functions:v0.1.1
    environment:
      - APP_PORT=3000
    ports:
      - "3000:3000"

volumes:
  worker-data:
  truth-data:
